version: '3.8'

########################
#  NETWORK + VOLUMES   #
########################
networks:
  concert-net:

volumes:
  db-data:

########################
#      SERVICES        #
########################
services:

  ########################
  # MySQL 8.3 container  #
  ########################
  db:
    image: mysql:8.3
    container_name: concert-mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: concertdb
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: concert
      MYSQL_PASSWORD: concertpass
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p$${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - concert-net

  ########################
  # Spring-Boot backend  #
  ########################
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: concert-backend
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      #######################
      #  DataSource
      #######################
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/concertdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: concert
      SPRING_DATASOURCE_PASSWORD: concertpass

      #######################
      #  JPA
      #######################
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "false"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect

      #######################
      #  JWT
      #######################
      SECURITY_JWT_SECRET: MzJieXRlc2xvbmdrZXl3aXRobnVtYmVyczEyMzQ1Ng==
      SECURITY_JWT_EXPIRATION_MS: 86400000
      SECURITY_JWT_REFRESH_EXPIRATION_MS: 604800000

      #######################
      #  Force port 8080  👈
      #######################
      SERVER_PORT: "8080"          # overrides EB’s PORT=80

      #######################
      #  JVM tuning
      #######################
      JAVA_TOOL_OPTIONS: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0"

    ports:
      - "8080:8080"
    networks:
      - concert-net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5