version: '3'
services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://db:3306/concertdb?useSSL=false&allowPublicKeyRetrieval=true"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "password"
      SPRING_DATASOURCE_DRIVER: "com.mysql.cj.jdbc.Driver"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_DIALECT: "org.hibernate.dialect.MySQL8Dialect"
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: concertdb
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3307:3306"

