name: Concert Server CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out code
      - name: Check out code
        uses: actions/checkout@v3

      # 2) Set up Java 17 (Temurin)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3) Cache Maven packages
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      # 4) Build with Maven
      - name: Build with Maven
        run: mvn clean install --batch-mode

      # 5) Run tests
      - name: Run tests
        run: mvn test --batch-mode

      # 6) Build Docker Image
      - name: Build Docker Image
        run: docker build -t concert-management-server .

      # 7) Run Docker Compose and perform health check
      - name: Build Docker Image and Run Container with Docker Compose
        run: |
          docker compose up -d --build
          # Wait for the backend to fully start. Adjust sleep as needed.
          sleep 60
          docker compose logs backend
          curl -f http://localhost:8080/actuator/health || (echo "Health check failed" && exit 1)
          docker compose down
        shell: bash
        
