name: Full CI/CD

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  build-and-test-backend:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:8.3
        env:
          MYSQL_DATABASE: concertdb
          MYSQL_ROOT_PASSWORD: password
          MYSQL_USER: concert
          MYSQL_PASSWORD: concertpass
        # no ports: mapping, so it only lives on the docker network
        options: >-
          --health-cmd="mysqladmin ping -h localhost -ppassword"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Check out backend
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build & verify with Maven
        run: mvn clean verify --batch-mode

      - name: Build backend Docker image
        run: |
          docker build \
            --build-arg GIT_SHA=${{ github.sha }} \
            -t concert-management-server:${{ github.sha }} \
            .

      - name: Install cosign
        run: |
          wget https://github.com/sigstore/cosign/releases/latest/download/cosign-linux-amd64 -O cosign
          chmod +x cosign
          sudo mv cosign /usr/local/bin/

      - name: Sign Docker image
        run: |
          # NOTE: replace the --key reference with your own key location
          cosign sign \
            --key k8s://sigstore-cosign-secret \
            concert-management-server:${{ github.sha }}

      - name: Bring up stack & health check
        run: |
          docker compose up -d --build
          sleep 30
          docker compose logs backend
          curl -f http://localhost:8080/actuator/health
        shell: bash

      - name: Tear down
        if: always()
        run: docker compose down
        shell: bash

  audit-and-build-frontend:
    name: Frontend Audit & Build
    runs-on: ubuntu-latest
    needs: build-and-test-backend

    steps:
      # 1) Check out your frontend repo into ./frontend
      - name: Check out frontend
        uses: actions/checkout@v3
        with:
          # **Adjust this** to your actual GitHub org/user and repo name
          repository: YOUR_GITHUB_ORG/concert-management-frontend
          path: frontend

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install & audit dependencies
        working-directory: frontend
        run: |
          npm ci
          npm audit --production

      - name: Build frontend
        working-directory: frontend
        run: npm run build
