name: Concert Server CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:8.3
        env:
          MYSQL_DATABASE: concertdb
          MYSQL_ROOT_PASSWORD: password
          MYSQL_USER: concert
          MYSQL_PASSWORD: concertpass
        ports:
          - 3307:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -ppassword"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5s

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build & test backend
        run: |
          mvn clean verify -B

      - name: Build Docker image
        run: |
          docker build \
            --build-arg GIT_SHA=${{ github.sha }} \
            -t concert-management-server:${{ github.sha }} \
            .

      - name: Install cosign
        run: |
          wget https://github.com/sigstore/cosign/releases/latest/download/cosign-linux-amd64 -O cosign
          chmod +x cosign
          sudo mv cosign /usr/local/bin/

      - name: Sign Docker image
        run: |
          cosign sign \
            --key k8s://sigstore-cosign-secret \
            concert-management-server:${{ github.sha }}

      - name: Run Docker Compose & Health Check
        run: |
          docker compose up -d --build
          sleep 30
          docker compose logs backend
          curl -f http://localhost:8080/actuator/health || (echo "Health check failed" && exit 1)
          docker compose down
        shell: bash

  audit-frontend:
    name: Frontend Security & Build
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Check out frontend
        uses: actions/checkout@v3
        with:
          # assumes your frontend lives in a sibling repo; adjust if it's in mono‐repo
          repository: your-org/concert-management-frontend
          path: frontend

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install & audit
        working-directory: frontend
        run: |
          npm ci
          npm audit --production

      - name: Build frontend
        working-directory: frontend
        run: npm run build
