name: Concert Server CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  build-and-test-backend:
    runs-on: ubuntu-latest
    env:
      COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
    services:
      db:
        image: mysql:8.3
        env:
          MYSQL_DATABASE: concertdb
          MYSQL_ROOT_PASSWORD: password
          MYSQL_USER: concert
          MYSQL_PASSWORD: concertpass
        options: >-
          --health-cmd="mysqladmin ping -h localhost -ppassword"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5s

    steps:
      - name: Check out back-end
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Build & test back-end
        run: mvn clean verify -B

      - name: Build Docker image
        run: |
          docker build \
            --build-arg GIT_SHA=${{ github.sha }} \
            -t concert-management-server:${{ github.sha }} \
            .

      - name: Install cosign
        run: |
          wget https://github.com/sigstore/cosign/releases/latest/download/cosign-linux-amd64 -O cosign
          chmod +x cosign
          sudo mv cosign /usr/local/bin/

      - name: Sign Docker image
        run: |
          cosign sign \
            --key k8s://sigstore-cosign-secret \
            concert-management-server:${{ github.sha }}

      - name: Run Docker Compose & Health Check
        run: |
          docker compose up -d --build
          sleep 30
          docker compose logs backend
          curl -f http://localhost:8080/actuator/health || (echo "Health check failed" && exit 1)
          docker compose down
        shell: bash

  audit-and-build-frontend:
    name: Front-end Audit & Build
    runs-on: ubuntu-latest
    needs: build-and-test-backend

    steps:
      - name: Check out front-end
        uses: actions/checkout@v3
        with:
          repository: StevenScript/concert-management-frontend
          path: frontend
          token: ${{ secrets.FRONTEND_PAT }}

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install & audit dependencies
        working-directory: frontend
        run: |
          npm ci
          npm audit --production

      - name: Build front-end
        working-directory: frontend
        run: npm run build